packages:
  - packages/*

allowBuilds:
  esbuild: true
  "@scarf/scarf": true
  cpu-features: true
  puppeteer: true
  ssh2: true
  "@bufbuild/buf": true
  "@confluentinc/kafka-javascript": true

catalog:
  "@anatine/zod-mock": 3.14.0
  "@apidevtools/swagger-parser": 10.1.1
  "@aws-sdk/client-dynamodb": 3.840.0
  "@aws-sdk/client-kms": 3.840.0
  "@aws-sdk/client-s3": 3.842.0
  "@aws-sdk/client-sesv2": 3.840.0
  "@aws-sdk/client-sqs": 3.840.0
  "@aws-sdk/s3-request-presigner": 3.842.0
  "@aws-sdk/util-dynamodb": 3.840.0
  "@faker-js/faker": 8.4.1
  "@pagopa/eslint-config": 3.0.0
  "@protobuf-ts/plugin": 2.9.4
  "@protobuf-ts/protoc": 2.9.4
  "@protobuf-ts/runtime": 2.9.4
  "@stoplight/spectral-cli": 6.15.0
  "@tsconfig/node-lts": 20.1.3
  "@tsconfig/strictest": 2.0.5
  "@types/adm-zip": 0.5.7
  "@types/archiver": 6.0.2
  "@types/express": 4.17.21
  "@types/html2json": 1.0.4
  "@types/json-diff": 1.0.3
  "@types/jsonwebtoken": 9.0.10
  "@types/lodash.isempty": 4.4.9
  "@types/lodash.isequal": 4.5.8
  "@types/multer": 1.4.13
  "@types/node": 20.19.9
  "@types/nodemailer": 6.4.17
  "@types/pg": 8.11.11
  "@types/qs": 6.9.15
  "@types/ssh2-sftp-client": 9.0.5
  "@types/supertest": 6.0.3
  "@types/swagger-ui-express": 4.1.8
  "@xmldom/xmldom": 0.9.8
  "@zodios/core": 10.9.6
  "@zodios/express": 10.6.1
  adm-zip: 0.5.16
  archiver: 7.0.1
  aws-msk-iam-sasl-signer-js: 1.0.1
  aws-sdk-client-mock: 4.0.1
  axios: 1.12.0
  axios-logger: 2.8.1
  camelcase-keys: 9.1.3
  connection-string: 4.4.0
  cpx2: 7.0.2
  csv: 6.3.11
  csv-stringify: 6.5.2
  date-fns: 4.1.0
  date-fns-tz: 3.1.3
  dotenv: 16.4.7
  dotenv-flow: 4.1.0
  drizzle-kit: 0.30.4
  drizzle-orm: 0.39.3
  drizzle-zod: 0.7.1
  eslint: 8.57.1
  express: 4.20.0
  fast-xml-parser: 5.3.4
  form-data-encoder: 4.1.0
  handlebars: 4.7.8
  html2json: 1.0.2
  jose: 5.9.4
  json-diff: 1.0.6
  jsonwebtoken: 9.0.2
  jwks-rsa: 3.1.0
  kafkajs: 2.2.4
  knip: 5.75.1
  lodash.isempty: 4.4.0
  lodash.isequal: 4.5.0
  mime: 4.0.7
  mkdirp: 3.0.1
  multer: 2.0.2
  nodemailer: 7.0.11
  octokit: 4.1.4
  openapi-types: 12.1.3
  openapi-zod-client: 1.18.3
  openapi3-ts: 3.1.0
  p-limit: 6.2.0
  p-retry: 6.2.1
  pg: 8.13.1
  pg-promise: 11.8.0
  prettier: 2.8.8
  prettier-plugin-organize-imports: 4.2.0
  puppeteer: 22.11.2
  qs: 6.14.2
  rate-limiter-flexible: 5.0.5
  redis: 4.6.15
  ssh2-sftp-client: 9.1.0
  supertest: 7.0.0
  swagger-ui-express: 5.0.1
  testcontainers: 10.9.0
  ts-pattern: 5.2.0
  tsc-esm-fix: 2.20.27
  tsx: 4.19.1
  turbo: 2.2.3
  typescript: 5.4.5
  uuid: 13.0.0
  vitest: 4.0.18
  winston: 3.16.0
  xml-crypto: 6.0.1
  yaml: 2.4.5
  zod: 3.23.8
  zod-validation-error: 3.3.0

catalogMode: strict
