export * as agreementApi from "./agreementApi.js";
export * as attributeRegistryApi from "./attributeRegistryApi.js";
export * as authorizationApi from "./generated/authorizationApi.js";
export * as authorizationManagementApi from "./generated/authorizationManagementApi.js";
export * as bffApi from "./bffApi.js";
export * as catalogApi from "./catalogApi.js";
export * as purposeApi from "./purposeApi.js";
export * as selfcareV2ClientApi from "./generated/selfcareV2ClientApi.js";
export * as tenantApi from "./generated/tenantApi.js";
export * as apiGatewayApi from "./apiGatewayApi.js";
export * from "./selfcareClients.js";
