import { CatalogProcessApiEServiceDescriptor } from "./api/catalogTypes.js";
import { TenantProcessApiResponse } from "./api/tenantTypes.js";

/* 
  NOTE:
  The "certifiedAttributesSatisfied" implementation follows the same logic
  as the code in `packages/agreement-process/src/model/domain/validators.ts`, 
  except for the models it handles. 
  The BFF uses the model from the response generated by the client API, 
  which is different from the model used in the validator of the agreement-process package.
  To minimize conversion complexity and code duplication, we have replicated this validator. 
  If this continues to grow, consider moving this code to a shared package.
*/
export const certifiedAttributesSatisfied = (
  descriptor: CatalogProcessApiEServiceDescriptor,
  tenant: TenantProcessApiResponse
): boolean => {
  const tenantCertifiedAttributes = tenant.attributes
    .map((att) => att.certified)
    .filter((att) => att && !att.revocationTimestamp);

  const consumerCertifiedAttributesIds = tenantCertifiedAttributes.map(
    (a) => a?.id
  );

  return descriptor.attributes.certified.every((attributeList) => {
    const descriptorCertifiedAttributes = attributeList.map((a) => a.id);
    return (
      descriptorCertifiedAttributes.filter((id) =>
        consumerCertifiedAttributesIds.includes(id)
      ).length > 0
    );
  });
};
