import { Category, Institution } from "../src/services/openDataExtractor.js";

export const agency: Institution[] = [
  {
    id: "12345678901",
    originId: "Z1234ABC",
    taxCode: "12345678901",
    category: "SA",
    description: "Municipality of Example City",
    digitalAddress: "example@pec.city.gov",
    address: "Main Street 1",
    zipCode: "12345",
    origin: "IPA",
    kind: "Stazioni Appaltanti",
    classification: "Agency",
  },
  {
    id: "98765432109",
    originId: "Z5678DEF",
    taxCode: "98765432109",
    category: "L37",
    description: "Example Health Services",
    digitalAddress: "health@pec.services.org",
    address: "Health Avenue 12",
    zipCode: "67890",
    origin: "IPA",
    kind: "Gestori di Pubblici Servizi",
    classification: "Agency",
  },
  {
    id: "87654321098",
    originId: "Z9123GHI",
    taxCode: "87654321098",
    category: "L33",
    description: "Example Educational Institute",
    digitalAddress: "education@pec.institute.edu",
    address: "Education Road 5",
    zipCode: "54321",
    origin: "IPA",
    kind: "Pubbliche Amministrazioni",
    classification: "Agency",
  },
  {
    id: "76543210987",
    originId: "Z3456JKL",
    taxCode: "76543210987",
    category: "SA",
    description: "Example Transportation Services",
    digitalAddress: "transport@pec.services.org",
    address: "Transport Street 9",
    zipCode: "87654",
    origin: "IPA",
    kind: "Stazioni Appaltanti",
    classification: "Agency",
  },
  {
    id: "65432109876",
    originId: "Z6789MNO",
    taxCode: "65432109876",
    category: "SAG",
    description: "Example Energy Company",
    digitalAddress: "energy@pec.company.com",
    address: "Energy Lane 3",
    zipCode: "98765",
    origin: "IPA",
    kind: "Gestori di Pubblici Servizi",
    classification: "Agency",
  },
];

export const aoo: Institution[] = [
  {
    id: "90012345678",
    originId: "B2A2H8J",
    taxCode: "90012345678",
    category: "SA",
    description: "SCPGI - Scuola Primaria Giovanni Pascoli",
    digitalAddress: "scpgi@pec.istruzione.it",
    address: "Via Dante Alighieri, 12",
    zipCode: "37015",
    origin: "IPA",
    kind: "Stazioni Appaltanti",
    classification: "AOO",
  },
  {
    id: "90098765432",
    originId: "C3B3I9K",
    taxCode: "90098765432",
    category: "L37",
    description: "ICMAR - Istituto Comprensivo G. Marconi",
    digitalAddress: "icmar@pec.istruzione.it",
    address: "Piazza Garibaldi, 1",
    zipCode: "58013",
    origin: "IPA",
    kind: "Gestori di Pubblici Servizi",
    classification: "AOO",
  },
  {
    id: "90123456789",
    originId: "D4C4J0L",
    taxCode: "90123456789",
    category: "L33",
    description: "SSAL - Scuola Secondaria di I Grado Alighieri",
    digitalAddress: "ssal@pec.istruzione.it",
    address: "Corso Italia, 25",
    zipCode: "87030",
    origin: "IPA",
    kind: "Pubbliche Amministrazioni",
    classification: "AOO",
  },
  {
    id: "90234567890",
    originId: "E5D5K1M",
    taxCode: "90234567890",
    category: "SA",
    description: "ITLDV - Istituto Tecnico Leonardo da Vinci",
    digitalAddress: "itldv@pec.istruzione.it",
    address: "Viale Roma, 30",
    zipCode: "12045",
    origin: "IPA",
    kind: "Stazioni Appaltanti",
    classification: "AOO",
  },
  {
    id: "90345678901",
    originId: "F6E6L2N",
    taxCode: "90345678901",
    category: "SAG",
    description: "LCVIR - Liceo Classico Virgilio",
    digitalAddress: "lcvir@pec.istruzione.it",
    address: "Via Milano, 42",
    zipCode: "44022",
    origin: "IPA",
    kind: "Gestori di Pubblici Servizi",
    classification: "AOO",
  },
];

export const uo: Institution[] = [
  {
    id: "80576370584",
    originId: "CXY56D",
    taxCode: "80576370584",
    category: "SA",
    description:
      "Ufficio per la transizione al Digitale - AZIENDA SANITARIA LOCALE ROMA 1",
    digitalAddress: "segreteria.asl@pec.it",
    address: "Via Roma, 100",
    zipCode: "00152",
    origin: "IPA",
    kind: "Stazioni Appaltanti",
    classification: "UO",
  },
  {
    id: "91045670482",
    originId: "KJ4W9T",
    taxCode: "91045670482",
    category: "L37",
    description:
      "Ufficio per la transizione al Digitale - LICEO SCIENTIFICO STATALE GALILEO GALILEI",
    digitalAddress: "rtd@liceogalilei.it",
    address: "Via Galilei, 45",
    zipCode: "00153",
    origin: "IPA",
    kind: "Gestori di Pubblici Servizi",
    classification: "UO",
  },
  {
    id: "92067380495",
    originId: "JQXA93",
    taxCode: "92067380495",
    category: "L33",
    description:
      "Ufficio per la transizione al Digitale - ISTITUTO TECNICO INDUSTRIALE STATALE LEONARDO DA VINCI",
    digitalAddress: "itdavinci@pec.it",
    address: "Via Leonardo, 27",
    zipCode: "40127",
    origin: "IPA",
    kind: "Pubbliche Amministrazioni",
    classification: "UO",
  },
  {
    id: "80234560327",
    originId: "LX82QR",
    taxCode: "80234560327",
    category: "SA",
    description: "Ufficio Amministrativo - AZIENDA OSPEDALIERA POLICLINICO",
    digitalAddress: "amministrazione@pec.policlinico.it",
    address: "Piazza Duomo, 12",
    zipCode: "20121",
    origin: "IPA",
    kind: "Stazioni Appaltanti",
    classification: "UO",
  },
  {
    id: "12345678901",
    originId: "MN43JW",
    taxCode: "12345678901",
    category: "SAG",
    description: "Ufficio Tecnico - COMUNE DI NAPOLI",
    digitalAddress: "comune.napoli@pec.it",
    address: "Piazza Municipio, 1",
    zipCode: "80100",
    origin: "IPA",
    kind: "Gestori di Pubblici Servizi",
    classification: "UO",
  },
];

export const categories: Category[] = [
  {
    code: "C18",
    name: "Fondazioni per la Ricerca Scientifica",
    kind: "Enti di Ricerca Pubblici",
    origin: "IPA",
  },
  {
    code: "L41",
    name: "Consorzi di Sviluppo Turistico",
    kind: "Pubbliche Amministrazioni",
    origin: "IPA",
  },
  {
    code: "C22",
    name: "Enti di Promozione Sportiva",
    kind: "Enti Nazionali di Sport e Benessere",
    origin: "IPA",
  },
  {
    code: "L14",
    name: "Aziende per la Gestione dell'Acqua",
    kind: "Pubbliche Amministrazioni",
    origin: "IPA",
  },
  {
    code: "C23",
    name: "Federazioni delle Industrie Creative",
    kind: "Pubbliche Amministrazioni",
    origin: "IPA",
  },
  {
    code: "L25",
    name: "Consorzi di Bonifica",
    kind: "Pubbliche Amministrazioni",
    origin: "IPA",
  },
  {
    code: "C20",
    name: "Enti per la Salvaguardia Ambientale",
    kind: "Enti Nazionali Ambientali",
    origin: "IPA",
  },
  {
    code: "L26",
    name: "Agenzie per la Digitalizzazione della PA",
    kind: "Pubbliche Amministrazioni",
    origin: "IPA",
  },
  {
    code: "L29",
    name: "Enti per la Tutela dei Diritti dei Consumatori",
    kind: "Pubbliche Amministrazioni",
    origin: "IPA",
  },
  {
    code: "C19",
    name: "Enti Pubblici di Controllo Sanitario",
    kind: "Enti Nazionali Sanitari",
    origin: "IPA",
  },
  {
    code: "L9",
    name: "Istituti per la Formazione Professionale",
    kind: "Pubbliche Amministrazioni",
    origin: "IPA",
  },
  {
    code: "L27",
    name: "Consorzi per l'Energia Sostenibile",
    kind: "Pubbliche Amministrazioni",
    origin: "IPA",
  },
  {
    code: "C21",
    name: "Enti di Regolazione dei Trasporti",
    kind: "Enti Nazionali di Trasporto",
    origin: "IPA",
  },
  {
    code: "L48",
    name: "Agenzie Regionali per lo Sviluppo Sostenibile",
    kind: "Pubbliche Amministrazioni",
    origin: "IPA",
  },
  {
    code: "C25",
    name: "Fondazioni Pubbliche per l'Istruzione",
    kind: "Pubbliche Amministrazioni",
    origin: "IPA",
  },
  {
    code: "L50",
    name: "Agenzie per la Tutela del Paesaggio",
    kind: "Pubbliche Amministrazioni",
    origin: "IPA",
  },
  {
    code: "L32",
    name: "Autorità per la Sicurezza Alimentare",
    kind: "Pubbliche Amministrazioni",
    origin: "IPA",
  },
  {
    code: "C24",
    name: "Enti per lo Sviluppo Tecnologico",
    kind: "Enti Nazionali di Innovazione",
    origin: "IPA",
  },
  {
    code: "L49",
    name: "Agenzie per la Ristrutturazione Urbana",
    kind: "Pubbliche Amministrazioni",
    origin: "IPA",
  },
  {
    code: "C26",
    name: "Enti di Regolazione delle Telecomunicazioni",
    kind: "Enti Nazionali delle Comunicazioni",
    origin: "IPA",
  },
];

export const attributes = [
  {
    code: "C18",
    description: "Fondazioni per la Ricerca Scientifica",
    name: "Fondazioni per la Ricerca Scientifica",
    origin: "IPA",
  },
  {
    code: "L41",
    description: "Consorzi di Sviluppo Turistico",
    name: "Consorzi di Sviluppo Turistico",
    origin: "IPA",
  },
  {
    code: "C22",
    description: "Enti di Promozione Sportiva",
    name: "Enti di Promozione Sportiva",
    origin: "IPA",
  },
  {
    code: "L14",
    description: "Aziende per la Gestione dell'Acqua",
    name: "Aziende per la Gestione dell'Acqua",
    origin: "IPA",
  },
  {
    code: "C23",
    description: "Federazioni delle Industrie Creative",
    name: "Federazioni delle Industrie Creative",
    origin: "IPA",
  },
  {
    code: "L25",
    description: "Consorzi di Bonifica",
    name: "Consorzi di Bonifica",
    origin: "IPA",
  },
  {
    code: "C20",
    description: "Enti per la Salvaguardia Ambientale",
    name: "Enti per la Salvaguardia Ambientale",
    origin: "IPA",
  },
  {
    code: "L26",
    description: "Agenzie per la Digitalizzazione della PA",
    name: "Agenzie per la Digitalizzazione della PA",
    origin: "IPA",
  },
  {
    code: "L29",
    description: "Enti per la Tutela dei Diritti dei Consumatori",
    name: "Enti per la Tutela dei Diritti dei Consumatori",
    origin: "IPA",
  },
  {
    code: "C19",
    description: "Enti Pubblici di Controllo Sanitario",
    name: "Enti Pubblici di Controllo Sanitario",
    origin: "IPA",
  },
  {
    code: "L9",
    description: "Istituti per la Formazione Professionale",
    name: "Istituti per la Formazione Professionale",
    origin: "IPA",
  },
  {
    code: "L27",
    description: "Consorzi per l'Energia Sostenibile",
    name: "Consorzi per l'Energia Sostenibile",
    origin: "IPA",
  },
  {
    code: "C21",
    description: "Enti di Regolazione dei Trasporti",
    name: "Enti di Regolazione dei Trasporti",
    origin: "IPA",
  },
  {
    code: "L48",
    description: "Agenzie Regionali per lo Sviluppo Sostenibile",
    name: "Agenzie Regionali per lo Sviluppo Sostenibile",
    origin: "IPA",
  },
  {
    code: "C25",
    description: "Fondazioni Pubbliche per l'Istruzione",
    name: "Fondazioni Pubbliche per l'Istruzione",
    origin: "IPA",
  },
  {
    code: "L50",
    description: "Agenzie per la Tutela del Paesaggio",
    name: "Agenzie per la Tutela del Paesaggio",
    origin: "IPA",
  },
  {
    code: "L32",
    description: "Autorità per la Sicurezza Alimentare",
    name: "Autorità per la Sicurezza Alimentare",
    origin: "IPA",
  },
  {
    code: "C24",
    description: "Enti per lo Sviluppo Tecnologico",
    name: "Enti per lo Sviluppo Tecnologico",
    origin: "IPA",
  },
  {
    code: "L49",
    description: "Agenzie per la Ristrutturazione Urbana",
    name: "Agenzie per la Ristrutturazione Urbana",
    origin: "IPA",
  },
  {
    code: "C26",
    description: "Enti di Regolazione delle Telecomunicazioni",
    name: "Enti di Regolazione delle Telecomunicazioni",
    origin: "IPA",
  },
  {
    code: "290d1371af230243db2c12eaaaa465ffd1457f06c91d8a14b7c5bca8d4e29bdf",
    description: "Pubbliche Amministrazioni",
    name: "Agenzie per la Ristrutturazione Urbana",
    origin: "IPA",
  },
  {
    code: "Z1234ABC",
    description: "Municipality of Example City",
    name: "Municipality of Example City",
    origin: "IPA",
  },
  {
    code: "Z5678DEF",
    description: "Example Health Services",
    name: "Example Health Services",
    origin: "IPA",
  },
  {
    code: "Z9123GHI",
    description: "Example Educational Institute",
    name: "Example Educational Institute",
    origin: "IPA",
  },
  {
    code: "Z3456JKL",
    description: "Example Transportation Services",
    name: "Example Transportation Services",
    origin: "IPA",
  },
  {
    code: "Z6789MNO",
    description: "Example Energy Company",
    name: "Example Energy Company",
    origin: "IPA",
  },
];
