documentationUrl: https://github.com/italia/api-oas-checker-rules
extends:
  [
    "https://github.com/italia/api-oas-checker-rules/releases/download/1.1/spectral-modi.yml",
  ]
overrides:
  - files:
      - packages/api-clients/open-api/selfcareV2ClientApi.yml
      - packages/api-clients/open-api/authorizationManagementApi.yaml
      - packages/api-clients/open-api/notifierApi.yml
    rules:
      "*": off
rules:
  servers-use-https: off
  paths-status: off # Enable this once authorization server migration is completes and we can remove the /authorization-server prefix