export const PUBLIC_ADMINISTRATIONS_IDENTIFIER = "IPA";
export const CONTRACT_AUTHORITY_PUBLIC_SERVICES_MANAGERS = "SAG";
export const PUBLIC_SERVICES_MANAGERS = "L37";
export const SCP = "PDND_INFOCAMERE-SCP";
