/* eslint-disable */
// @generated by protobuf-ts 2.9.1 with parameter eslint_disable
// @generated from protobuf file "v1/events.proto" (package "catalog", syntax proto2)
// tslint:disable

/* 
  This type was generated by protobuf definied in 
  https://github.com/pagopa/interop-be-catalog-management/blob/1.0.x/src/main/protobuf/v1/catalog-item.proto
  with commit 86f8a640f9543d45536cec7b61011269e4494c4d
*/

/**
 * @generated from protobuf message catalog.CatalogItemV1
 */
export interface CatalogItemV1 {
  /**
   * @generated from protobuf field: string id = 1;
   */
  id: string;
  /**
   * @generated from protobuf field: string producerId = 2;
   */
  producerId: string;
  /**
   * @generated from protobuf field: string name = 3;
   */
  name: string;
  /**
   * @generated from protobuf field: string description = 4;
   */
  description: string;
  /**
   * @generated from protobuf field: catalog.CatalogItemTechnologyV1 technology = 5;
   */
  technology: CatalogItemTechnologyV1;
  /**
   * @generated from protobuf field: optional catalog.CatalogAttributesV1 attributes = 6;
   */
  attributes?: CatalogAttributesV1;
  /**
   * @generated from protobuf field: repeated catalog.CatalogDescriptorV1 descriptors = 7;
   */
  descriptors: CatalogDescriptorV1[];
  /**
   * @generated from protobuf field: optional int64 createdAt = 8;
   */
  createdAt?: bigint;
  /**
   * @generated from protobuf field: repeated catalog.CatalogItemRiskAnalysisV1 riskAnalysis = 9;
   */
  riskAnalysis: CatalogItemRiskAnalysisV1[];
  /**
   * @generated from protobuf field: optional catalog.CatalogItemModeV1 mode = 10;
   */
  mode?: CatalogItemModeV1;
}
/**
 * @generated from protobuf message catalog.CatalogItemRiskAnalysisV1
 */
export interface CatalogItemRiskAnalysisV1 {
  /**
   * @generated from protobuf field: string id = 1;
   */
  id: string;
  /**
   * @generated from protobuf field: string name = 2;
   */
  name: string;
  /**
   * @generated from protobuf field: catalog.CatalogRiskAnalysisFormV1 riskAnalysisForm = 3;
   */
  riskAnalysisForm?: CatalogRiskAnalysisFormV1;
  /**
   * @generated from protobuf field: int64 createdAt = 4;
   */
  createdAt: bigint;
}
/**
 * @generated from protobuf message catalog.CatalogRiskAnalysisFormV1
 */
export interface CatalogRiskAnalysisFormV1 {
  /**
   * @generated from protobuf field: string id = 1;
   */
  id: string;
  /**
   * @generated from protobuf field: string version = 2;
   */
  version: string;
  /**
   * @generated from protobuf field: repeated catalog.CatalogRiskAnalysisSingleAnswerV1 singleAnswers = 3;
   */
  singleAnswers: CatalogRiskAnalysisSingleAnswerV1[];
  /**
   * @generated from protobuf field: repeated catalog.CatalogRiskAnalysisMultiAnswerV1 multiAnswers = 4;
   */
  multiAnswers: CatalogRiskAnalysisMultiAnswerV1[];
}
/**
 * @generated from protobuf message catalog.CatalogRiskAnalysisSingleAnswerV1
 */
export interface CatalogRiskAnalysisSingleAnswerV1 {
  /**
   * @generated from protobuf field: string id = 1;
   */
  id: string;
  /**
   * @generated from protobuf field: string key = 2;
   */
  key: string;
  /**
   * @generated from protobuf field: optional string value = 3;
   */
  value?: string;
}
/**
 * @generated from protobuf message catalog.CatalogRiskAnalysisMultiAnswerV1
 */
export interface CatalogRiskAnalysisMultiAnswerV1 {
  /**
   * @generated from protobuf field: string id = 1;
   */
  id: string;
  /**
   * @generated from protobuf field: string key = 2;
   */
  key: string;
  /**
   * @generated from protobuf field: repeated string values = 3;
   */
  values: string[];
}
/**
 * @generated from protobuf message catalog.CatalogAttributeValueV1
 */
export interface CatalogAttributeValueV1 {
  /**
   * @generated from protobuf field: string id = 1;
   */
  id: string;
  /**
   * @generated from protobuf field: bool explicitAttributeVerification = 2;
   */
  explicitAttributeVerification: boolean;
}
/**
 * @generated from protobuf message catalog.CatalogAttributeV1
 */
export interface CatalogAttributeV1 {
  /**
   * @generated from protobuf field: optional catalog.CatalogAttributeValueV1 single = 1;
   */
  single?: CatalogAttributeValueV1;
  /**
   * @generated from protobuf field: repeated catalog.CatalogAttributeValueV1 group = 2;
   */
  group: CatalogAttributeValueV1[];
}
/**
 * @generated from protobuf message catalog.CatalogAttributesV1
 */
export interface CatalogAttributesV1 {
  /**
   * @generated from protobuf field: repeated catalog.CatalogAttributeV1 certified = 1;
   */
  certified: CatalogAttributeV1[];
  /**
   * @generated from protobuf field: repeated catalog.CatalogAttributeV1 declared = 2;
   */
  declared: CatalogAttributeV1[];
  /**
   * @generated from protobuf field: repeated catalog.CatalogAttributeV1 verified = 3;
   */
  verified: CatalogAttributeV1[];
}
/**
 * @generated from protobuf message catalog.CatalogDescriptorV1
 */
export interface CatalogDescriptorV1 {
  /**
   * @generated from protobuf field: string id = 1;
   */
  id: string;
  /**
   * @generated from protobuf field: string version = 2;
   */
  version: string;
  /**
   * @generated from protobuf field: optional string description = 3;
   */
  description?: string;
  /**
   * @generated from protobuf field: repeated catalog.CatalogDocumentV1 docs = 4;
   */
  docs: CatalogDocumentV1[];
  /**
   * @generated from protobuf field: catalog.CatalogDescriptorStateV1 state = 5;
   */
  state: CatalogDescriptorStateV1;
  /**
   * @generated from protobuf field: optional catalog.CatalogDocumentV1 interface = 6;
   */
  interface?: CatalogDocumentV1;
  /**
   * @generated from protobuf field: repeated string audience = 7;
   */
  audience: string[];
  /**
   * @generated from protobuf field: int32 voucherLifespan = 8;
   */
  voucherLifespan: number;
  /**
   * @generated from protobuf field: int32 dailyCallsPerConsumer = 9;
   */
  dailyCallsPerConsumer: number;
  /**
   * @generated from protobuf field: int32 dailyCallsTotal = 10;
   */
  dailyCallsTotal: number;
  /**
   * @generated from protobuf field: optional catalog.AgreementApprovalPolicyV1 agreementApprovalPolicy = 11;
   */
  agreementApprovalPolicy?: AgreementApprovalPolicyV1;
  /**
   * @generated from protobuf field: optional int64 createdAt = 12;
   */
  createdAt?: bigint;
  /**
   * @generated from protobuf field: optional int64 publishedAt = 13;
   */
  publishedAt?: bigint;
  /**
   * @generated from protobuf field: repeated string serverUrls = 14;
   */
  serverUrls: string[];
  /**
   * @generated from protobuf field: optional int64 suspendedAt = 15;
   */
  suspendedAt?: bigint;
  /**
   * @generated from protobuf field: optional int64 deprecatedAt = 16;
   */
  deprecatedAt?: bigint;
  /**
   * @generated from protobuf field: optional int64 archivedAt = 17;
   */
  archivedAt?: bigint;
  /**
   * @generated from protobuf field: optional catalog.CatalogAttributesV1 attributes = 18;
   */
  attributes?: CatalogAttributesV1;
}
/**
 * @generated from protobuf message catalog.CatalogDocumentV1
 */
export interface CatalogDocumentV1 {
  /**
   * @generated from protobuf field: string id = 1;
   */
  id: string;
  /**
   * @generated from protobuf field: string name = 2;
   */
  name: string;
  /**
   * @generated from protobuf field: string contentType = 3;
   */
  contentType: string;
  /**
   * @generated from protobuf field: string path = 4;
   */
  path: string;
  /**
   * @generated from protobuf field: string checksum = 5;
   */
  checksum: string;
  /**
   * @generated from protobuf field: string uploadDate = 6;
   */
  uploadDate: string;
  /**
   * @generated from protobuf field: string prettyName = 7;
   */
  prettyName: string;
}
/**
 * @generated from protobuf message catalog.CatalogItemV1AddedV1
 */
export interface CatalogItemV1AddedV1 {
  /**
   * @generated from protobuf field: catalog.CatalogItemV1 catalogItem = 1;
   */
  catalogItem?: CatalogItemV1;
}
/**
 * @generated from protobuf message catalog.ClonedCatalogItemV1AddedV1
 */
export interface ClonedCatalogItemV1AddedV1 {
  /**
   * @generated from protobuf field: catalog.CatalogItemV1 catalogItem = 1;
   */
  catalogItem?: CatalogItemV1;
}
/**
 * @generated from protobuf message catalog.CatalogItemV1UpdatedV1
 */
export interface CatalogItemV1UpdatedV1 {
  /**
   * @generated from protobuf field: catalog.CatalogItemV1 catalogItem = 1;
   */
  catalogItem?: CatalogItemV1;
}
/**
 * @generated from protobuf message catalog.CatalogItemWithDescriptorsDeletedV1
 */
export interface CatalogItemWithDescriptorsDeletedV1 {
  /**
   * @generated from protobuf field: catalog.CatalogItemV1 catalogItem = 1;
   */
  catalogItem?: CatalogItemV1;
  /**
   * @generated from protobuf field: string descriptorId = 2;
   */
  descriptorId: string;
}
/**
 * @generated from protobuf message catalog.CatalogItemDocumentUpdatedV1
 */
export interface CatalogItemDocumentUpdatedV1 {
  /**
   * @generated from protobuf field: string eServiceId = 1;
   */
  eServiceId: string;
  /**
   * @generated from protobuf field: string descriptorId = 2;
   */
  descriptorId: string;
  /**
   * @generated from protobuf field: string documentId = 3;
   */
  documentId: string;
  /**
   * @generated from protobuf field: catalog.CatalogDocumentV1 updatedDocument = 4;
   */
  updatedDocument?: CatalogDocumentV1;
  /**
   * @generated from protobuf field: repeated string serverUrls = 5;
   */
  serverUrls: string[];
}
/**
 * @generated from protobuf message catalog.CatalogItemDeletedV1
 */
export interface CatalogItemDeletedV1 {
  /**
   * @generated from protobuf field: string catalogItemId = 1;
   */
  catalogItemId: string;
}
/**
 * @generated from protobuf message catalog.CatalogItemDocumentAddedV1
 */
export interface CatalogItemDocumentAddedV1 {
  /**
   * @generated from protobuf field: string eServiceId = 1;
   */
  eServiceId: string;
  /**
   * @generated from protobuf field: string descriptorId = 2;
   */
  descriptorId: string;
  /**
   * @generated from protobuf field: catalog.CatalogDocumentV1 document = 3;
   */
  document?: CatalogDocumentV1;
  /**
   * @generated from protobuf field: bool isInterface = 4;
   */
  isInterface: boolean;
  /**
   * @generated from protobuf field: repeated string serverUrls = 5;
   */
  serverUrls: string[];
}
/**
 * @generated from protobuf message catalog.CatalogItemDocumentDeletedV1
 */
export interface CatalogItemDocumentDeletedV1 {
  /**
   * @generated from protobuf field: string eServiceId = 1;
   */
  eServiceId: string;
  /**
   * @generated from protobuf field: string descriptorId = 2;
   */
  descriptorId: string;
  /**
   * @generated from protobuf field: string documentId = 3;
   */
  documentId: string;
}
/**
 * @generated from protobuf message catalog.CatalogItemDescriptorAddedV1
 */
export interface CatalogItemDescriptorAddedV1 {
  /**
   * @generated from protobuf field: string eServiceId = 1;
   */
  eServiceId: string;
  /**
   * @generated from protobuf field: catalog.CatalogDescriptorV1 catalogDescriptor = 2;
   */
  catalogDescriptor?: CatalogDescriptorV1;
}
/**
 * @generated from protobuf message catalog.CatalogItemDescriptorUpdatedV1
 */
export interface CatalogItemDescriptorUpdatedV1 {
  /**
   * @generated from protobuf field: string eServiceId = 1;
   */
  eServiceId: string;
  /**
   * @generated from protobuf field: catalog.CatalogDescriptorV1 catalogDescriptor = 2;
   */
  catalogDescriptor?: CatalogDescriptorV1;
}
/**
 * @generated from protobuf message catalog.MovedAttributesFromEserviceToDescriptorsV1
 */
export interface MovedAttributesFromEserviceToDescriptorsV1 {
  /**
   * @generated from protobuf field: catalog.CatalogItemV1 catalogItem = 1;
   */
  catalogItem?: CatalogItemV1;
}
/**
 * @generated from protobuf message catalog.CatalogItemRiskAnalysisAddedV1
 */
export interface CatalogItemRiskAnalysisAddedV1 {
  /**
   * @generated from protobuf field: catalog.CatalogItemV1 catalogItem = 1;
   */
  catalogItem?: CatalogItemV1;
  /**
   * @generated from protobuf field: string catalogRiskAnalysisId = 2;
   */
  catalogRiskAnalysisId: string;
}
/**
 * @generated from protobuf message catalog.CatalogItemRiskAnalysisUpdatedV1
 */
export interface CatalogItemRiskAnalysisUpdatedV1 {
  /**
   * @generated from protobuf field: catalog.CatalogItemV1 catalogItem = 1;
   */
  catalogItem?: CatalogItemV1;
  /**
   * @generated from protobuf field: string catalogRiskAnalysisId = 2;
   */
  catalogRiskAnalysisId: string;
}
/**
 * @generated from protobuf message catalog.CatalogItemRiskAnalysisDeletedV1
 */
export interface CatalogItemRiskAnalysisDeletedV1 {
  /**
   * @generated from protobuf field: catalog.CatalogItemV1 catalogItem = 1;
   */
  catalogItem?: CatalogItemV1;
  /**
   * @generated from protobuf field: string catalogRiskAnalysisId = 2;
   */
  catalogRiskAnalysisId: string;
}
/**
 * @generated from protobuf enum catalog.CatalogDescriptorStateV1
 */
export enum CatalogDescriptorStateV1 {
  /**
   * @generated synthetic value - protobuf-ts requires all enums to have a 0 value
   */
  UNSPECIFIED$ = 0,
  /**
   * @generated from protobuf enum value: DRAFT = 1;
   */
  DRAFT = 1,
  /**
   * @generated from protobuf enum value: PUBLISHED = 2;
   */
  PUBLISHED = 2,
  /**
   * @generated from protobuf enum value: DEPRECATED = 3;
   */
  DEPRECATED = 3,
  /**
   * @generated from protobuf enum value: SUSPENDED = 4;
   */
  SUSPENDED = 4,
  /**
   * @generated from protobuf enum value: ARCHIVED = 5;
   */
  ARCHIVED = 5,
}
/**
 * @generated from protobuf enum catalog.CatalogItemTechnologyV1
 */
export enum CatalogItemTechnologyV1 {
  /**
   * @generated synthetic value - protobuf-ts requires all enums to have a 0 value
   */
  UNSPECIFIED$ = 0,
  /**
   * @generated from protobuf enum value: REST = 1;
   */
  REST = 1,
  /**
   * @generated from protobuf enum value: SOAP = 2;
   */
  SOAP = 2,
}
/**
 * @generated from protobuf enum catalog.AgreementApprovalPolicyV1
 */
export enum AgreementApprovalPolicyV1 {
  /**
   * @generated synthetic value - protobuf-ts requires all enums to have a 0 value
   */
  UNSPECIFIED$ = 0,
  /**
   * @generated from protobuf enum value: AUTOMATIC = 1;
   */
  AUTOMATIC = 1,
  /**
   * @generated from protobuf enum value: MANUAL = 2;
   */
  MANUAL = 2,
}
/**
 * @generated from protobuf enum catalog.CatalogItemModeV1
 */
export enum CatalogItemModeV1 {
  /**
   * @generated synthetic value - protobuf-ts requires all enums to have a 0 value
   */
  UNSPECIFIED$ = 0,
  /**
   * @generated from protobuf enum value: RECEIVE = 1;
   */
  RECEIVE = 1,
  /**
   * @generated from protobuf enum value: DELIVER = 2;
   */
  DELIVER = 2,
}
